### ISSUE TITLE
ejabberd_auth_jwt not working with ejabberd 16.08

### ISSUE THREAD

**Issue by ales-smokvina** [ParamountVentures/ejabberd-auth-jwt#2]
I have tried to make it work with ejabberd 16.08, following error is thrown in log

2016-08-24 10:19:51.945 [error] <0.38.0>@ejabberd_config:validate_opts:934 ignoring option 'auth_method' with invalid value: [jwt]

**Comment by prateekgera1987** [comment]
I am also trying to configure it with ejabberd 16.04 but unable to compile main erl file for this module.Can someone confirm that jwt auth works with ejabbered or not.

**Comment by ales-smokvina** [comment]
I got it working on 16.02. Be sure to use erlc from ejabberd distribution.

**Comment by prateekgera1987** [comment]
I am using https://www.process-one.net/downloads/ejabberd/16.02/ejabberd-16.02-0.x86_64.rpm
this one now.

**Comment by prateekgera1987** [comment]
getting crash logs [error] CRASH REPORT Process <0.442.0> with 0 neighbours crashed with reason: call to undefined function ejwt:parse_jwt

**Comment by stevenlivz** [comment]
I am upgrading to 16.09 just now so will see what i run into.

**Comment by stevenlivz** [comment]
Seems to break between 16.03 and 16.04 ... i am trying to figure out why.

**Comment by stevenlivz** [comment]
Ok - i have a fix for this now. I will update this morning.

**Comment by prateekgera1987** [comment]
so you are trying with 16.09 if I am correct.Please update fix we are waiting to get it resolved

**Comment by stevenlivz** [comment]
@prateekgera1987 i have committed an update that will allow it to work with ejabberd 16.04 and onwards. I have just compiled it with 16.09 and it works fine. Please note you now need to compile it with the source as ejabberd authentication modules can no longer be dropped in as beam files. This may change in future.

**Comment by prateekgera1987** [comment]
@stevenlivz followed all steps mentioned with 16.09 and getting below error while checking with xmpp client 
10:58:40.433 [error] gen_fsm <0.452.0> in state wait_for_feature_request terminated with reason: call to undefined function ejwt:parse_jwt
   I am using to login with a user and jwt token in tkabber client.

**Comment by stevenlivz** [comment]
Have you compiled and dropped the dependencies into the same folder (the ejabberd ebin folder). Sounds like the ejwt beam may be missing and that is a dependency.

I added links to the dependencies here https://github.com/ParamountVentures/ejabberd-auth-jwt

**Comment by prateekgera1987** [comment]
Above error is gone by compiling and copying ejwt.beam to /lib/ejabberd-16.09/ebin .I am trying to login with existing account in ejabberd not creating new account getting 16:41:45.226 [info]({socket_state,gen_tcp,#Port<0.12017>,<0.462.0>}) Failed authentication for admin@localhost from x.x.x.x
16:41:45.226 [info] Invalid Claim for admin for as admin@localhost

**Comment by prateekgera1987** [comment]
Thanks Steven its working like a charm now :).It was my bad I was passing domain in user_id while creating jwt auth

**Comment by stevenlivz** [comment]
That's great news. Hopefully I will get time to make it more stable over the coming months.
